name: culinfo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  banner_carousel: ^1.2.1
  expandable_text: ^2.3.0
  sqflite: ^2.3.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.8
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  insta_image_viewer: ^1.0.4
  intl: ^0.19.0
  page_transition: ^2.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
